# Generated by Django 2.0.1 on 2018-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('album_logo', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=200)),
                ('song_title', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete=None, to='music.Album')),
            ],
        ),
    ]
