# Generated by Django 2.0.1 on 2018-01-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180123_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='file_type',
            field=models.FileField(upload_to=''),
        ),
    ]
