# Generated by Django 2.0.1 on 2018-01-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
    ]
