# Generated by Django 2.0.1 on 2018-01-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_favourite',
        ),
    ]
